- name: Installer Apache2 et créer une page web avec GIF
  hosts: all
  
  tasks:
    - name: Mise à jour du cache des paquets
      become: yes
      apt:
        update_cache: yes

    - name: Installer Apache2
      become: yes
      apt:
        name: apache2
        state: present

    - name: Créer le répertoire pour le site web
      become: yes
      file:
        path: /var/www/html
        state: directory

    
    - name: Créer le fichier index.html avec un formulaire de recherche et le GIF
      become: yes
      copy:
        content: |
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Ma Page Web</title>
          </head>
          <body>
              <div style="text-align: center; margin-top: 100px;">
                  <img src="/gille_tourne.gif" alt="Before GIF" width="320" height="240">
                  <h1>
                      <img src="/gille_tourne.gif" alt="Left of Title GIF" width="100" height="100">
                      Coucou, je suis une page web
                      <img src="/gille_tourne.gif" alt="Right of Title GIF" width="100" height="100">
                  </h1>
                  <img src="/gille_tourne.gif" alt="After GIF" width="320" height="240">
                  <form action="https://www.google.com/search" method="GET">
                      <input type="text" name="q" placeholder="Recherche Google">
                      <input type="submit" value="Rechercher">
                  </form>
                  <img src="/gille.gif" alt="GIF" width="320" height="240">
              </div>
          </body>
          </html>



        dest: /var/www/html/index.html

    - name: Redémarrer Apache2
      become: yes
      service:
        name: apache2
        state: restarted
